freq: 20
# start_now: -1
# start_togo: 0

start_now: 2
start_togo: 5
oriParam: 0
tolerence: 20
decelerationZone: 30
nodeLoseConpDELAY: 2
secondCapt: 290
thirdCapt: 400
after_6_shift: 40
time_6: 2
# time_7: 2
# time_6: 30
time_7: 15