odom_mode: 0
freq: 20

start_now: -1
start_togo: 0

oriParam: 0
tolerence: 30
decelerationZone: 30
nodeLoseConpDELAY: 15
X_after_over_hurdles: 300
after_6_shift: 40
# time_6: 30
time_7: 30


# after_6_shift: 100
time_6: 3
# time_7: 2

# constant
span: 0.1
# phy_maxMS: 30
phy_maxMS: 200
slowMS: 15

# soft
softRate: 0.7

# tracker param
black: 0
nonblack: 1

# deceleration
deceleration_coeff: 0.8
deceleration_minSpeed: 5

# variable
# cmd_vel
ori: -1

# V: 30
V: 100
vel_limit: 20

# transmission fix

vkp: 9
# vkp: 5.0
vki: 0.0
vkd: 0.0

# rotation fix

wkp: 1.5
# wkp: 0.9
wki: 0.0
wkd: 0.0
